Fix TypeError
When calling /schemas/{schema_id}/write_record, a server error 500 occurrs. The log output says

    TypeError: inject() got an unexpected keyword argument 'required'

Signed-off-by: Gorgsenegger <mail@gorgs.org>